
language: generic

services:
  - docker

before_install:
- docker pull carlad/sinatra
- docker run -d  carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
- bundle exec rake test
